# Code Sandboxes examples

PYTHON ?= python

.PHONY: all local-eval local-docker local-jupyter datalayer-runtime

all: local-eval local-docker local-jupyter datalayer-runtime

local-eval:
	$(PYTHON) local_eval_example.py

local-docker:
	$(PYTHON) local_docker_example.py

local-jupyter:
	$(PYTHON) local_jupyter_example.py

datalayer-runtime:
	$(PYTHON) datalayer_runtime_example.py
