# Code Sandboxes examples

PYTHON ?= python

.PHONY: all eval docker jupyter datalayer

all: eval docker jupyter datalayer

eval:
	$(PYTHON) local_eval_example.py

docker:
	$(PYTHON) local_docker_example.py

jupyter:
	$(PYTHON) local_jupyter_example.py

datalayer:
	$(PYTHON) datalayer_runtime_example.py
