# Copyright (c) 2025-2026 Datalayer, Inc.
#
# BSD 3-Clause License

"""The JSON Schema of the Environment specification, exported from its models.

The pydantic models are the source; this schema is what other languages
generate their types from, so it is regenerated by command and checked for
drift rather than edited:

    python -m code_sandboxes.environments schema --write
    python -m code_sandboxes.environments schema --check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from .spec import API_VERSION, Environment

__all__ = ["SCHEMA_ID", "default_schema_path", "environment_schema", "schema_text"]

SCHEMA_ID = "https://datalayer.io/schemas/environments/v1alpha1/environment.json"


def environment_schema() -> dict[str, Any]:
    schema = Environment.model_json_schema(by_alias=True)
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["$id"] = SCHEMA_ID
    schema["title"] = "Environment"
    schema["description"] = f"A Datalayer Environment, {API_VERSION}."
    return schema


def schema_text() -> str:
    return json.dumps(environment_schema(), indent=2, sort_keys=True) + "\n"


def default_schema_path() -> Path:
    """``schemas/environment-v1alpha1.json`` at the root of the repository."""
    return Path(__file__).resolve().parents[2] / "schemas" / "environment-v1alpha1.json"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m code_sandboxes.environments schema")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", metavar="PATH", nargs="?", const="", help="write the schema")
    group.add_argument("--check", metavar="PATH", nargs="?", const="", help="fail on drift")
    arguments = parser.parse_args(argv)
    text = schema_text()
    if arguments.check is not None:
        path = Path(arguments.check) if arguments.check else default_schema_path()
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            print(f"{path} is out of date; regenerate it with --write", file=sys.stderr)  # noqa: T201 - a command's own output
            return 1
        return 0
    path = Path(arguments.write) if arguments.write else default_schema_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
